name: russian_words
description: >
  Utilities for working with Russian words. Generates
  well-sounding word combinations, and provides access to ~33000 Russian
  words.
version: 0.2.0
homepage: https://github.com/RenatFakhrutdinov/russian_words

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  test: ^1.20.1